import { type NextPage } from "next";
import Head from "next/head";
import localFont from "@next/font/local";
import { useRef, useState } from "react";
import { IntersectObserv } from "../components/IntersectObs";
import { ScrollDirection } from "../components/ScrollDirection";

const myFont = localFont({ src: "../../public/FuturaLight.ttf" });

//todo:
// each div gets a ref
// on scroll, check if the ref is in the viewport
// if it is, add the class to the div
// if it isn't, remove the class from the div

const Home: NextPage = () => {
  const project1 = useRef<HTMLDivElement>(null);
  const project2 = useRef<HTMLDivElement>(null);

  const { fadeCSS: fadeCSS1, innerFadeCSS: innerFadeCSS1 } =
    IntersectObserv(project1);
  const { fadeCSS: fadeCSS2, innerFadeCSS: innerFadeCSS2 } =
    IntersectObserv(project2);
  const { scrollDir } = ScrollDirection();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="fixed h-5 w-full bg-slate-100"></div>
      <div className="fixed h-full w-5 bg-slate-100"></div>
      <div className="fixed bottom-0 h-5 w-full bg-slate-100"></div>
      <div className="fixed right-0 h-full w-5 bg-slate-100"></div>
      <main className="snap-y snap-proximity">
        <div className="flex justify-end gap-4 pr-10">
          <div className="mt-8 inline-block h-8 w-8 rounded-[50%] bg-offGrey"></div>
          <div className="mt-8 inline-block h-8 w-8 rounded-[50%] bg-offGrey"></div>
          <div className="mt-8 inline-block h-8 w-8 rounded-[50%] bg-offGrey"></div>
        </div>
        <div className="mr-11 flex justify-end gap-6 pt-2">
          <div className="verticalText">About</div>
          <div className="verticalText">Contact</div>
          <div className="verticalText">Blog</div>
        </div>
        <div className="h-full w-full text-offGrey">
          <h2 className="ml-5 mt-28 text-[18rem] font-medium leading-none tracking-[0.01em]">
            Benjamin
          </h2>
          <h2 className="ml-5 mt-2 text-[18rem] font-medium leading-none tracking-[0.001em]">
            Margoli<p className="inline pl-[0.21rem]">u</p>s
          </h2>
        </div>

        <div className="flex h-[300vh]">
          <div>
            <div
              ref={project1}
              className="sticky top-0 mt-32 flex h-screen w-fit flex-col items-start justify-between pl-12 text-2xl text-offGrey"
            >
              <div className="flex flex-col items-start">
                <h2 className={`mt-12 text-4xl ${fadeCSS1}`}>
                  <div className={innerFadeCSS1}>01</div>
                </h2>
                <h3 className={`mt-32 ml-8 -indent-1 text-8xl ${fadeCSS1}`}>
                  <div className={innerFadeCSS1}>Reactime</div>
                </h3>
                <h3 className={`mt-16 ml-8 ${fadeCSS1}`}>
                  <div className={innerFadeCSS1}>Full Stack Developer</div>
                </h3>
                <span
                  className={`mt-4 ml-8 text-4xl ${myFont.className} ${fadeCSS1}`}
                >
                  <div className={innerFadeCSS1}>
                    React time-travel debugger, that allows developers <br /> to
                    jump through time in their React application
                  </div>
                </span>
              </div>
              <h3 className={`mb-12 font-medium ${fadeCSS1}`}>
                <div className={innerFadeCSS1}>Chrome Extension + Website</div>
              </h3>
            </div>
          </div>
          <div className="">
            <img
              src="laptop1.jpg"
              className="mt-[100vh] ml-8 h-[40vh]"
              alt="laptop"
            />
            <img
              src="laptop2.jpg"
              className="ml-[50vh] h-[35vh]"
              alt="laptop"
            />
            <img src="laptop3.jpg" className="ml-8 h-[30vh]" alt="laptop" />
          </div>
        </div>

        {/* //TODO: Figure out how position stickey works */}
        <div className="mt-[-100vh] flex">
          <div className="">
            <div
              ref={project2}
              className="sticky top-0 flex h-screen w-fit flex-col items-start justify-between pl-12 text-2xl text-offGrey"
            >
              <div className="flex flex-col items-start">
                <h2 className={`mt-12 text-4xl ${fadeCSS2}`}>
                  <div className={innerFadeCSS2}>02</div>
                </h2>
                <h3
                  className={`mt-28 ml-8 pb-4 -indent-1 text-8xl ${fadeCSS2}`}
                >
                  <div className={innerFadeCSS2}>Dev2Dev</div>
                </h3>
                <h3 className={`mt-16 ml-8 ${fadeCSS2}`}>
                  <div className={innerFadeCSS2}>Full Stack Developer</div>
                </h3>
                <div
                  className={`mt-4 ml-8 text-4xl ${myFont.className} ${fadeCSS2}`}
                >
                  <div className={innerFadeCSS2}>
                    A chat room that pairs junior and senior develoeprs <br />
                    to help developers learn, grow, and develop as a community
                  </div>
                </div>
              </div>
              <h3 className={`mb-12 font-medium ${fadeCSS2}`}>
                <div className={innerFadeCSS2}>Website</div>
              </h3>
            </div>
          </div>
          <div className="">
            <img
              src="laptop1.jpg"
              className="mt-[100vh] ml-8 h-[40vh]"
              alt="laptop"
            />
            <img
              src="laptop2.jpg"
              className="ml-[50vh] h-[35vh]"
              alt="laptop"
            />
            {/* <img src="laptop3.jpg" className="ml-8 h-[25vh]" alt="laptop" /> */}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
